# NAME: Joseph Picchi
# EMAIL: jpicchi22@g.ucla.edu


lab3b: lab3b.py
	ln -sf lab3b.py lab3b
	chmod a+x lab3b

dist:
	tar -czf lab3b-605124511.tar.gz Makefile README lab3b.py

clean:
	rm -f lab3b-605124511.tar.gz lab3b