# NAME: Joseph Picchi
# EMAIL: jpicchi22@g.ucla.edu

# targets
default: dist

clean:
	rm -f lab4a-605124511.tar.gz

dist: build_run.png connected.png copy.png git.png my_beaglebone.png Makefile README
	tar -czf lab4a-605124511.tar.gz $^
